name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔨 Maintenance'
    collapse-after: 5
    labels:
      - 'chore'
      - 'documentation'
      - 'github_actions'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'documentation'
      - 'dependencies'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## What's changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler: # assign labels to pr according to files having changed
  - label: 'python'
    files:
      - '*.py'
  - label: 'rust'
    files:
      - '*.rs'
  - label: 'documentation'
    files:
      - '*.md'
  - label: 'dependencies'
    files:
      - '*.lock'
      - 'pyproject.toml'
  - label: 'front'
    files:
      - '*.ts'
      - '*.tsx'
      - '*.html'
      - '*.css'
  - label: 'github_actions'
    files:
      - '.github/**/*.yml'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'