name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
      - 'dependencies'
change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## What's changed

  $CHANGES
autolabeler: # assign labels to pr according to files having changed
  - label: 'python'
    files:
      - '*.py'
  - label: 'rust'
    files:
      - '*.rs'
  - label: 'documentation'
    files:
      - '*.md'
  - label: 'dependencies'
    files:
      - '*.lock'
      - 'pyproject.toml'

# other labels: github_actions